export enum ActionsEnum {
    // Hero
    HERO_ACTION_ATTACK = "HERO_ACTION_ATTACK",
    HERO_ACTION_KO = "HERO_ACTION_KO",

    // Opponent
    OPPONENT_ACTION_ATTACK = "OPPONENT_ACTION_ATTACK",
    OPPONENT_ACTION_KO = "OPPONENT_ACTION_KO",
}
