export enum Action {
    HERO_ACTION_ATTACK = "HERO_ACTION_ATTACK",
    HERO_ACTION_DEFEATED = "HERO_ACTION_DEFEATED",
    OPPONENT_ACTION_ATTACK = "OPPONENT_ACTION_ATTACK",
    OPPONENT_ACTION_DEFEATED = "OPPONENT_ACTION_ATTACK",
}
