export enum AnimationEnum {
    HERO_ANIMATION_ATTACK = "HERO_ANIMATION_ATTACK",
    HERO_ANIMATION_DEFEATED = "HERO_ANIMATION_DEFEATED",
    OPPONENT_ANIMATION_ATTACK = "OPPONENT_ANIMATION_ATTACK",
    OPPONENT_ANIMATION_DEFEATED = "OPPONENT_ANIMATION_ATTACK",
}
